/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencyconverterjava;

import javax.swing.JOptionPane;

/**
 *
 * @author Prerna
 */
public class CurrencyConverter extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtamt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFrom = new javax.swing.JComboBox();
        txtTo = new javax.swing.JComboBox();
        Convert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO CURRENCY CONVERTER");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Amount");

        txtamt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("From");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("To");

        txtFrom.setBackground(new java.awt.Color(255, 102, 102));
        txtFrom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "INR", "EURO", "Thai Baht" }));
        txtFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromActionPerformed(evt);
            }
        });

        txtTo.setBackground(new java.awt.Color(255, 102, 102));
        txtTo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INR", "USD", "EURO", "Thai Baht" }));

        Convert.setBackground(new java.awt.Color(255, 153, 0));
        Convert.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Convert.setText("Convert");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtamt)
                        .addComponent(txtFrom, 0, 218, Short.MAX_VALUE)
                        .addComponent(txtTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromActionPerformed

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
       
            
        Double convert;
        Double amount=Double.parseDouble(txtamt.getText());
        
        
        
        if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="INR")
        {
            convert=amount*84.46;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" INR");
        }
        
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="EURO")
        {
            convert=amount*0.92;
            JOptionPane.showMessageDialog(this,"The amount is " +String.format("%.2f",convert)+ EUR");
        }
        
        else if(txtFrom.getSelectedItem().toString()=="USD" && txtTo.getSelectedItem().toString()=="Thai Baht")
        {
            convert=amount*35.39;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" THB");
        }
        
        else if(txtFrom.getSelectedItem().toString()=="INR" && txtTo.getSelectedItem().toString()=="USD")
        {
            convert=amount/84.46;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" USD");
        }
        else if(txtFrom.getSelectedItem().toString()=="INR" && txtTo.getSelectedItem().toString()=="EURO")
        {
            convert=amount/91.16;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" EUR");
        }
        
        else if(txtFrom.getSelectedItem().toString()=="INR" && txtTo.getSelectedItem().toString()=="Thai Baht")
        {
            convert=amount/2.36;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" THB");
        }
        
         else if(txtFrom.getSelectedItem().toString()=="EURO" && txtTo.getSelectedItem().toString()=="USD")
        {
            convert=amount*1.09;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" USD");
        }
        
         else if(txtFrom.getSelectedItem().toString()=="EURO" && txtTo.getSelectedItem().toString()=="INR")
        {
            convert=amount*91.16;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" INR");
        }
         else if(txtFrom.getSelectedItem().toString()=="EURO" && txtTo.getSelectedItem().toString()=="Thai Baht")
        {
            convert=amount*38.63;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" THB");
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Thai Baht" && txtTo.getSelectedItem().toString()=="USD")
        {
            convert=amount/35.39;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" USD");
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Thai Baht" && txtTo.getSelectedItem().toString()=="INR")
        {
            convert=amount*2.36;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" INR");
        }
        
         else if(txtFrom.getSelectedItem().toString()=="Thai Baht" && txtTo.getSelectedItem().toString()=="EURO")
        {
            convert=amount/38.63;
            JOptionPane.showMessageDialog(this,"The amount is "+String.format("%.2f",convert)+" EUR");
        }
        
       
    }//GEN-LAST:event_ConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox txtFrom;
    private javax.swing.JComboBox txtTo;
    private javax.swing.JTextField txtamt;
    // End of variables declaration//GEN-END:variables
}
